### ISSUE TITLE
Hugo Error .Site.IsMultiLingual during npm run dev

### ISSUE THREAD

**Issue by AliffZulhelmi** [thuliteio/thulite#496]
## Description

$ npm run dev

> user123@0.0.0 dev
> hugo server --disableFastRender --noHTTPCache

Watching for changes in C:\Users\user123\Documents\Thulite\thulite-project\{assets,content,layouts,node_modules,package.json,static}
Watching for config changes in C:\Users\user123\Documents\Thulite\thulite-project\config\_default, C:\Users\user123\Documents\Thulite\thulite-project\config\_default\menus
Start building sites …
hugo v0.136.4 windows/386 BuildDate=unknown

ERROR deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Use hugo.IsMultilingual instead.
Built in 556 ms
Error: error building site: TOCSS: failed to transform "/scss/app.scss" (text/x-scss). Check your Hugo installation; you need the extended version to build SCSS/SASS with transpiler set to 'libsass'.: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information

### Steps to reproduce
(I'm using Git Bash)

1. npm create thulite@latest
- Follow all the guides until
- Output:
Scaffolding project in C:\Users\user123\Documents\Thulite\thulite-project

Done. Now run:

  cd thulite-project
  npm install
  npm run dev

2. Open new window (Already in thulite-project dir.)
3. npm install
4. npm run dev
5. Error come out

### Expected result

Not Sure

### Actual result

ERROR deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Use hugo.IsMultilingual instead.

### Environment

Paste the information here as shown by:

 hugo -v
ERROR deprecated: --verbose was deprecated in Hugo v0.114.0 and will be removed in Hugo 0.137.0. use --logLevel info
Total in 2 ms
Error: Unable to locate config file or config directory. Perhaps you need to create a new site.
Run `hugo help new` for details.

$ node -v
v20.18.0

$ npm --version
8.19.4

**Comment by h-enk** [comment]
Thanks! See also https://github.com/thuliteio/doks/discussions/1302 — expect a new release in about an hour

**Comment by h-enk** [comment]
Fixed with [@thulite/doks-core v1.8.0](https://github.com/thuliteio/doks-core/releases/tag/v1.8.0) and [create-thulite v1.7.3](https://github.com/thuliteio/create-thulite/releases/tag/v1.7.3)
